/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddLinkDialog: typeof import('./src/components/AddLinkDialog.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DebugFirebaseAuth: typeof import('./src/components/DebugFirebaseAuth.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Firebase: typeof import('./src/components/Firebase.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareLinkList: typeof import('./src/components/ShareLinkList.vue')['default']
    UpdateLinkDialog: typeof import('./src/components/UpdateLinkDialog.vue')['default']
  }
}
