env:
  PACKAGE_ID: 3cm.app
on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/deploy-3cm.app-to-firebase-hosting-pull-request.yml
      - packages/${{env.PACKAGE_ID}}/**
jobs:
  deploy:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm -w packages/${{env.PACKAGE_ID}} i
          npm -w packages/${{env.PACKAGE_ID}} run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./packages/${{env.PACKAGE_ID}}
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_XX_3CM }}'
          projectId: xx-3cm
    continue-on-error: true
  notify:
    needs: deploy
    uses: ./.github/workflows/notify.yml
    secrets: inherit
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{env.PACKAGE_ID}}
