env:
  PACKAGE_ID: bash.3cm.app
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-bash.3cm.app-to-fleek.yml
      - packages/bash.3cm.app/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      # find id by command: `npx -w packages/bash.3cm.app fleek projects list`
      FLEEK_PROJECT_ID: ${{ secrets.PACKAGE_BASH_FLEEK_PROJECT_ID }}
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
    steps:
      - id: e
        run: |
          echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm -w packages/${{env.PACKAGE_ID}} i
          npx -w packages/${{env.PACKAGE_ID}} fleek sites deploy
      - id: extract_deployment_id
        run: |
          slug=$(jq -r .sites[0].slug ./packages/${{env.PACKAGE_ID}}/fleek.config.json)
          deploy_info="$(npx -w packages/${{env.PACKAGE_ID}} fleek sites deployments --slug $slug)"
          deployment_id=$(echo "$deploy_info"|grep RELEASE_COMPLETED|head -n 1| awk '{split($0,a," "); print a[1]}')
          if [ -z "$deployment_id" ]; then
            echo "$deploy_info"
            exit 2
          fi
          echo "deployment_id=${deployment_id}" >> $GITHUB_OUTPUT
      - uses: infraway/create-dns-record@v2.0
        with:
          type: "CNAME"
          name: "bash.3cm.app"
          content: "${{ steps.extract_deployment_id.outputs.deployment_id }}.fleekcdn.xyz"
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
    continue-on-error: true
  notify:
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
