env:
  PACKAGE_ID: 3cm.app
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-3cm.app-to-cloudflare.yml
      - packages/3cm.app/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: e
        run: |
          echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: |
          npm -w packages/${{env.PACKAGE_ID}} i
          npm -w packages/${{env.PACKAGE_ID}} run build
      # - uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     entryPoint: ./packages/${{env.PACKAGE_ID}}
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_XX_3CM }}'
      #     channelId: live
      #     projectId: xx-3cm
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKER }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # environment: dev
          workingDirectory: packages/${{env.PACKAGE_ID}}
          command: |
            pages deploy dist --project-name=3cm-app --branch=master --commit-dirty=true
  notify:
    if: cancelled() == false
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
