name: Deploy to Firebase Hosting on PR
'on':
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/deploy-3cm.app-to-firebase-hosting-pull-request.yml
      - "packages/3cm.app/**"

jobs:
  deploy:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm -w packages/www i
          npm -w packages/www run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./packages/www
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_XX_3CM }}'
          projectId: xx-3cm
    continue-on-error: true
  notify:
    needs: deploy
    uses: ./.github/workflows/notify.yml
    secrets: inherit
    with:
      conclusion: ${{ needs.deploy.result }}
      package: 3cm.app
