env:
  PACKAGE_ID: gooful.3cm.app
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-gooful.3cm.app-to-fleek.yml
      - packages/gooful.3cm.app/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      # npx -w packages/gooful.3cm.app/ fleek projects list
      # ID                         Name        Created At                Current
      # ------------------------------------------------------------------------
      # clwndumtx000uy6pv36imho6h  1oo.app     2024-05-26T10:14:27.094Z         
      # clwnc3zc50001100b5aebupvx  3cm.app     2024-05-26T09:25:43.973Z  ✅      
      # cm36krrli0001rm4o1qt67eoz  3cm's Team  2024-11-07T00:34:01.970Z
      FLEEK_PROJECT_ID: clwnc3zc50001100b5aebupvx
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
    steps:
      - id: e
        run: |
          echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm
      - run: |
          npm -w packages/${{env.PACKAGE_ID}} i
          npx -w packages/${{env.PACKAGE_ID}} fleek sites deploy
      - id: extract_deployment_id
        run: |
          slug=$(jq -r .sites[0].slug ./packages/${{env.PACKAGE_ID}}/fleek.config.json)
          deploy_info="$(npx -w packages/${{env.PACKAGE_ID}} fleek sites deployments --slug $slug)"
          deployment_id=$(echo "$deploy_info"|grep RELEASE_COMPLETED|head -n 1| awk '{split($0,a," "); print a[1]}')
          if [ -z "$deployment_id" ]; then
            echo "$deploy_info"
            exit 2
          fi
          echo "deployment_id=${deployment_id}" >> $GITHUB_OUTPUT
      - uses: infraway/create-dns-record@v2.0
        with:
          type: "CNAME"
          name: "gooful.3cm.app"
          content: "${{ steps.extract_deployment_id.outputs.deployment_id }}.fleekcdn.xyz"
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
  notify:
    if: cancelled() == false
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
