env:
  PACKAGE_ID: file.3cm.app
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-file.3cm.app-to-cloudflare.yml
      - packages/file.3cm.app/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
    steps:
      - id: e
        run: |
          echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKER }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # environment: dev
          workingDirectory: packages/${{env.PACKAGE_ID}}
          command: |
            pages deploy docs --project-name=file --branch=master
    continue-on-error: true
  notify:
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
