env:
  PACKAGE_ID: dic.3cm.app
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-dic.3cm.app-to-cloudflare.yml
      - packages/dic.3cm.app/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: e
        run: |
          echo "PROJECT_ID=${{env.PROJECT_ID}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          npm -w packages/${{env.PACKAGE_ID}} i
          npm -w packages/${{env.PACKAGE_ID}} run build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKER }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: packages/${{env.PACKAGE_ID}}
          command: |
            pages deploy dist --project-name=dic --branch=master
    continue-on-error: true
  notify:
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.steps.e.outputs.PROJECT_ID }}
