env:
  PACKAGE_ID: file.3cm.app
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-file.3cm.app-to-github.yml
      - packages/file.3cm.app/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
    steps:
      - id: e
        run: |
          echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - run: |
          npm -w packages/${{env.PACKAGE_ID}} i
          git config user.name "github-actions-bot"
          git config user.email "support+actions@github.com"
          git remote set-url origin git@github.com:3cm-app/file.3cm.app.git
          npm -w packages/${{env.PACKAGE_ID}} run deploy -- \
            -u "github-actions-bot <support+actions@github.com>" \
            --repo git@github.com:3cm-app/file.3cm.app.git \
            --cname file.3cm.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notify:
    if: cancelled() == false
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
