env:
  PACKAGE_ID: 3cm.app
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-3cm.app-to-firebase-hosting-merge.yml
      - packages/3cm.app/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
    steps:
      - id: e
        run: |
          echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - run: |
          npm -w packages/${{env.PACKAGE_ID}} i
          npm -w packages/${{env.PACKAGE_ID}} run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./packages/${{env.PACKAGE_ID}}
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_XX_3CM }}'
          channelId: live
          projectId: xx-3cm
    if: ${{ always() }}
  notify:
    needs: deploy
    if: ${{ always() }}
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
