env:
  PACKAGE_ID: test
on:
  push:
    branches:
      - master
    # cannot use runner environment variables in parts of a workflow that are processed by GitHub Actions
    # see: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#using-the-env-context-to-access-environment-variable-values
    paths:
      - .github/workflows/notify-test.yml
      - .github/workflows/notify.yml
      - .github/*.*
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
    steps:
      - id: e
        run: |
          echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
      - run: |
          exit 2
    # https://github.com/orgs/community/discussions/77915#discussioncomment-8409702
    continue-on-error: true
  notify:
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
