env:
  PACKAGE_ID: test
on:
  push:
    branches:
      - master
    # the paths can't use env
    paths:
      - .github/workflows/notify-test.yml
      - .github/workflows/notify.yml
      - .github/*.*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit 2
    # https://github.com/orgs/community/discussions/77915#discussioncomment-8409702
    continue-on-error: true
  # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow
  notify:
    needs: deploy
    uses: ./.github/workflows/notify.yml
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
    secrets: inherit
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{env.PACKAGE_ID}}
